### ISSUE TITLE
A

### ISSUE THREAD

**Issue by tbn-cn** [yiqing18/GLoCNet#1]
Why the data is same when I train same pictures 1 epoch or other epoch? And are you the author of this paper?

**Comment by tbn-cn** [comment]
The training code is so strange . When testing, how is the inputing mat fire  generated .

**Comment by tbn-cn** [comment]
How do you train your model, what dataset and what epoch, and the number of the pictures, can you introduce it specifically？

**Comment by tbn-cn** [comment]
你这代码用自己图像增强的图片以及标签作为训练数据集这种方法好吗，还有就是训练模型和测试模型不一样，区别于多了一个预过滤步骤，还有就是你训练的数据集多大，epoch多大，为什么我训练一张训练多张，训练一轮训练多轮得到的数据都大差不差，这让我很疑惑，亲爱的作者，可以解答一下吗

**Comment by yiqing18** [comment]
由于真实标签的标注需要大量的人力，所以我们采用随机生成变换矩阵来获取点集和标签。那么您是有更好的方法来解决这个问题么？我们方法的训练需要先训练net1, 再根据net1的结果去训练net2, 请问您也是按照这种顺序来重新训练的么？在训练好net1后，net2也能较快的收敛。训练的数据集有60张图像，15个epoch就可以获得较好的效果了。此外，我们在利用net1获取到的邻点构建邻域时就已经剔除了很多容易分辨的outlier，这使得net2在初始状态就能得到一个相对优良的结果，所以我们在测试时通常会仿照RFM-SCAN等的方法，随机生成outlier来降低内点率。 我们方法的输入是点集，就算您的训练数据只有一张图片，那么每次迭代也会随机产生不一样的点集。

**Comment by tbn-cn** [comment]
Okay, what you said is quite similar to my understanding. Sorry if my language was a bit too direct.

**Comment by tbn-cn** [comment]
好的，谢谢回答，那您测试的时候，输入点集也是自己制作的吗

**Comment by yiqing18** [comment]
测试的数据都是需要人工标注的真实图像

**Comment by tbn-cn** [comment]
我的意思是说那个输入的mat文件，因为很多原始数据集的标注并不那样的，而您的模型输入不是包含image1,2,point1,2,gt的mat文件吗

**Comment by tbn-cn** [comment]
也就是说您的测试集，或者说是实验用到的数据集也都是输入单张图片，通过随机透视仿射变换生成目标图像，进而生成对应的mat文件然后用于测试的吗

**Comment by tbn-cn** [comment]
也就是说您的测试集，或者说是实验用到的数据集也都是输入单张图片，通过随机透视仿射变换生成目标图像，进而生成初始匹配以及对应标签存于mat文件然后用于测试的吗
